export const GAME_QUESTIONS_SET = "GAME_QUESTIONS_SET"
export const GAME_ANSWER_CHOICE = "GAME_ANSWER_CHOICE"
export const GAME_QUESTION_NEW = "GAME_QUESTION_NEW"
export const GAME_RESET = "GAME_RESET"
